name: methylseg
channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.11
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - numba
  - pyarrow
  - hmmlearn
  - umap-learn
  - pip
  - ipykernel
  - ca-certificates
  - openssl
  - pyyaml
  - conda-forge::panel
  - plotly
